### ISSUE TITLE
if possible can you provide a online purchase link (amazon etc) for your height-adjustable table?

### ISSUE THREAD

**Issue by pavanyogi** [Alwinator/aw-watcher-table#3]
If you have other recommendations(based on your experiences) then also please let us know.

**Comment by Alwinator** [comment]
It is a custom-made table from Neudoerfler (See [neudoerfler.com](https://www.neudoerfler.com/produkte/tische/arbeitstische))

**Comment by Alwinator** [comment]
I bought [this one](https://www.amazon.de/-/en/gp/product/B07N76L4YS) for other apartment of mine, and it is great so far.

**Comment by Pavanyogi121** [comment]
Yaa, very nice. Thanks for recommendations.
