### ISSUE TITLE
README outdated and with typo

### ISSUE THREAD

**Issue by smnmsr** [Alwinator/aw-watcher-table#5]
- In the description of the module autostart there's a typo: `"aw-table-watcher"` instead of `"aw-watcher-table"`
- it is not the file `aw-qt.ini` anymore
- the README lacks information on the installation of the visualization

**Comment by Alwinator** [comment]
This should be fixed with your PR, right?

**Comment by smnmsr** [comment]
> This should be fixed with your PR, right?

Not completely honestly. 

I didn‘t change the .ini extension. (Forgot to)

Also I did nothing on the visualization, but this is more of a bigger FR I guess, since it‘s not only about how to install the visu.

so if you don’t plan to add a visualization, I‘d suggest to close this issue for now.
